linters:
  enable:
    - staticcheck
    - errcheck
    - govet
    - ineffassign
    - misspell
    - noctx
    - exhaustive
    - goimports

linters-settings:
  staticcheck:
    checks: ["all"]

issues:
  max-same-issues: 0
  exclude-use-default-excludes: false
